// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pdb

type CompletedRequest struct {
	ID   int64  `json:"id"`
	User string `json:"user"`
}

type Postcard struct {
	ID string `json:"id"`
}

type PostmarkBouncedEmail struct {
	ID          string `json:"id"`
	Bounced     int64  `json:"bounced"`
	Recipient   string `json:"recipient"`
	Sender      string `json:"sender"`
	Description string `json:"description"`
	Details     string `json:"details"`
}

type PostmarkDeliveredEmail struct {
	ID     string `json:"id"`
	Sender string `json:"sender"`
}

type PostmarkInboundEmail struct {
	ID         string `json:"id"`
	Received   int64  `json:"received"`
	Email      string `json:"email"`
	FromName   string `json:"from_name"`
	Subject    string `json:"subject"`
	Message    string `json:"message"`
	Attachment []byte `json:"attachment"`
}

type PostmarkInboundRule struct {
	ID      int64  `json:"id"`
	Created int64  `json:"created"`
	Rule    string `json:"rule"`
}

type PostmarkOutboundEmail struct {
	ID     string `json:"id"`
	Sent   int64  `json:"sent"`
	Email  string `json:"email"`
	Sender string `json:"sender"`
	Status int64  `json:"status"`
}

type PostmarkSpamComplaint struct {
	ID string `json:"id"`
}

type PostmarkTemplate struct {
	ID string `json:"id"`
}

type QueuedRequest struct {
	ID          string `json:"id"`
	User        string `json:"user"`
	ToEmail     string `json:"to_email"`
	ToName      string `json:"to_name"`
	FromEmail   string `json:"from_email"`
	FromName    string `json:"from_name"`
	ArtworkEnum int64  `json:"artwork_enum"`
	StyleEnum   int64  `json:"style_enum"`
	BorderEnum  int64  `json:"border_enum"`
	FontEnum    int64  `json:"font_enum"`
	ShapeEnum   int64  `json:"shape_enum"`
	Country     string `json:"country"`
	Subject     string `json:"subject"`
	Message     string `json:"message"`
	Attachment  []byte `json:"attachment"`
}

type Recipient struct {
	ID       string `json:"id"`
	Created  int64  `json:"created"`
	Email    string `json:"email"`
	Received int64  `json:"received"`
}

type Sender struct {
	ID        string `json:"id"`
	Created   int64  `json:"created"`
	LastSent  int64  `json:"last_sent"`
	Email     string `json:"email"`
	Sent      int64  `json:"sent"`
	Fails     int64  `json:"fails"`
	Delivered int64  `json:"delivered"`
	Blocked   int64  `json:"blocked"`
}

type User struct {
	ID string `json:"id"`
}
