-- +goose Up
CREATE TABLE IF NOT EXISTS postcards (
    id TEXT PRIMARY KEY
) STRICT;

CREATE TABLE IF NOT EXISTS senders (
    id TEXT PRIMARY KEY,
    created INTEGER NOT NULL,
    last_sent INTEGER NOT NULL,
    email TEXT NOT NULL,
    sent INTEGER NOT NULL,
    fails INTEGER NOT NULL,
    delivered INTEGER NOT NULL,
    blocked INTEGER NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS recipients (
    id TEXT PRIMARY KEY,
    created INTEGER NOT NULL,
    email TEXT NOT NULL,
    received INTEGER NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY
);


-- +goose Down
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS recipients;
DROP TABLE IF EXISTS senders;
DROP TABLE IF EXISTS postcards;
